import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CONNECTIVITY2.java
 *
 * Created on Jan 28, 2016, 4:03:13 PM
 */

/**
 *
 * @author Alam singh
 */
public class CONNECTIVITY2 extends javax.swing.JFrame {

    /** Creates new form CONNECTIVITY2 */
    public CONNECTIVITY2() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        T = new javax.swing.JTable();
        S = new javax.swing.JButton();
        E = new javax.swing.JButton();
        SFCBX = new javax.swing.JComboBox();
        OCBX = new javax.swing.JComboBox();
        CTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        C = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        T.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ADM_NO", "ROLL_NO", "S_NAME", "PHYSICS", "CHEMISTRY", "MATHS", "ENGLISH", "IP", "BIOLOGY", "HINDI"
            }
        ));
        jScrollPane1.setViewportView(T);

        S.setText("Search in the Database");
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });

        E.setText("Empty Table");
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });

        SFCBX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ADM_NO", "ROLL_NO", "S_NAME", "PHYSICS", "CHEMISTRY", "MATHS", "ENGLISH", "IP", "BIOLOGY", "HINDI", " " }));
        SFCBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SFCBXActionPerformed(evt);
            }
        });

        OCBX.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">", "<", ">=", "<=" }));
        OCBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OCBXActionPerformed(evt);
            }
        });

        CTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTFActionPerformed(evt);
            }
        });

        jLabel1.setText("Criteria");

        jLabel2.setText("Search Field");

        jLabel3.setText("CLASS");

        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(SFCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addComponent(jLabel1)
                                        .addGap(54, 54, 54)
                                        .addComponent(CTF, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel3)
                                        .addGap(58, 58, 58)
                                        .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(E)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                        .addComponent(S)
                        .addGap(239, 239, 239))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SFCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OCBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E)
                    .addComponent(S))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SFCBXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SFCBXActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_SFCBXActionPerformed

    private void OCBXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OCBXActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_OCBXActionPerformed

    private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
E.doClick();
DefaultTableModel model=(DefaultTableModel)T.getModel();
try{
Class.forName("java.sql.Driver");
Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/data_analysis","root","");
Statement stmt =con.createStatement();
String sfld =(String)SFCBX.getSelectedItem();
String op=(String)OCBX.getSelectedItem();
String crit= CTF.getText();
String c= C.getText();
String query= "SELECT ADM_NO,ROLL_NO,S_NAME,PHYSICS,CHEMISTRY,MATHS,ENGLISH,IP,BIOLOGY,HINDI FROM SCIENCE_marks WHERE"+" "+sfld+" "+op+" "+crit+" "+"AND CLASS="+c+";";
ResultSet rs=stmt.executeQuery(query);
while(rs.next()){
model.addRow(new Object[]{
rs.getInt(1),rs.getInt(2),rs.getString(3),rs.getInt(4),rs.getInt(5),rs.getInt(6),rs.getInt(7),rs.getInt(8),rs.getInt(9),rs.getInt(10)
}  );
}
rs.close();
stmt.close();
con.close();
}
catch(Exception e){
    JOptionPane.showMessageDialog(null,"Error in connectivity");

}
}//GEN-LAST:event_SActionPerformed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
DefaultTableModel model= (DefaultTableModel)T.getModel();
int rows=model.getRowCount();
if(rows>0){
for(int i=0;i<rows;i++) {
model.removeRow(0);
}
}// TODO add your handling code here:
    }//GEN-LAST:event_EActionPerformed

    private void CTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CTFActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CONNECTIVITY2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField C;
    private javax.swing.JTextField CTF;
    private javax.swing.JButton E;
    private javax.swing.JComboBox OCBX;
    private javax.swing.JButton S;
    private javax.swing.JComboBox SFCBX;
    private javax.swing.JTable T;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
